name: Build on new or edited post

on:
  push:
    paths:
      - 'blog-md/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run build script
        run: bash ./build.sh
